### ISSUE TITLE
docker-compose-mode-helpers depends on f

### ISSUE THREAD

**Issue by paddy-hack** [meqif/docker-compose-mode#9]
Just tried to install this package (on emacs 24.4.1) and got this.
```

Compiling file /home/olaf/.emacs.d/elpa/docker-compose-mode-0.2.1/docker-compose-mode-helpers.el at Tue Aug  1 21:04:26 2017
Entering directory `/home/olaf/.emacs.d/elpa/docker-compose-mode-0.2.1/'
docker-compose-mode-helpers.el:22:1:Error: Cannot open load file: no such file or directory, f

Compiling file /home/olaf/.emacs.d/elpa/docker-compose-mode-0.2.1/docker-compose-mode.el at Tue Aug  1 21:04:26 2017
```
Looks like you're missing a dependency (or forgot to remove a require :wink:).

**Comment by meqif** [comment]
Hi! Thanks for reporting this issue. ❤️ 

The issue here is that that file is a helper that shouldn't be included in the MELPA package, and I totally forgot to update the recipe. I opened a pull request over at the MELPA repository (https://github.com/melpa/melpa/pull/4908), which hopefully will be merged soon.

**Comment by meqif** [comment]
This should be fixed in the next update of the package in MELPA (both in the stable or HEAD/tip). I'll close this issue, but feel free to re-open it if it isn't fixed. Thanks!

**Comment by paddy-hack** [comment]
Just confirmed that it installs fine without `f` now.  👍

**Comment by meqif** [comment]
Awesome, thank you!
